version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'creatify_interview'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 6

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - MYSQL_HOST=db
      - DB_NAME=creatify_interview
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql

#  test:
#    image: creatifyinterview_web:latest
#    command: /bin/bash
#    volumes:
#      - .:/code